# Docker Compose Override Example
# Copy this file to docker-compose.override.yml to customize the stack
# This file is ignored by git and allows for local customizations

version: '3.8'

services:
  # Example: Enable Traefik dashboard
  reverse-proxy:
    ports:
      - "8080:8080"  # Traefik dashboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      - "traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080"

  # Example: Add HTTPS support
  # reverse-proxy:
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./traefik/acme.json:/etc/traefik/acme.json
  #   labels:
  #     - "traefik.http.routers.netbox.tls=true"
  #     - "traefik.http.routers.netbox.tls.certresolver=letsencrypt"
  #     - "traefik.http.routers.nautobot.tls=true"
  #     - "traefik.http.routers.nautobot.tls.certresolver=letsencrypt"

  # Example: Add resource limits
  # netbox:
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: '0.5'
  #       reservations:
  #         memory: 512M
  #         cpus: '0.25'

  # Example: Add additional volumes for NetBox plugins
  # netbox:
  #   volumes:
  #     - ./plugins:/opt/netbox/netbox/plugins:ro
  #     - ./custom-fields:/opt/netbox/netbox/custom_fields:ro

  # Example: Enable PostgreSQL logging
  # postgres:
  #   command: postgres -c log_statement=all -c log_destination=stderr

  # Example: Add monitoring with Prometheus
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  #   networks:
  #     - netmgmt

  # Example: Add Grafana for visualization
  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   networks:
  #     - netmgmt

# volumes:
#   grafana-data:
